### PR TITLE
Implemented fetch crime api 

### PR DESCRIPTION
**Pull request by gehna-anand**
It provides the crime locations based on the user's location.
Please refer to the protocol doc here for more details on the API: [https://safemap-bigdata.atlassian.net/wiki/spaces/SafeMap/pages/491755/Fetch+crime+data+API]

### CODE REVIEW

**Review by pranjalagg — CHANGES_REQUESTED** [review]
Node modules should be excluded from the commit.

**Comment by deepanshusachdeva5** [comment]
start script missing in package.json, is the script running using node response.js ?

**Comment by deepanshusachdeva5** [comment]
Looks good!

**Review by deepanshusachdeva5 — APPROVED** [review]
Changes looks good!

**Review by pranjalagg — APPROVED** [review]

**Pull request merged**
